extragrant/extragrant/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('registration.backends.simple.urls')),
]

extragrant/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.result, name='result'),
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^recalc/$', views.recalc, name='recalc'),
    url(r'^voting/$', views.voting, name='voting'),
]

extragrant/polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User

# Create your models here.

@python_2_unicode_compatible
class Criterion(models.Model):
    code = models.CharField(max_length=10)
    description = models.CharField(max_length=500)

    def __str__(self):
        return (_("{code} : {description}")
                .format(code=self.code, description=self.description))

@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    average_score = models.FloatField(default=0)
    criterion = models.ForeignKey(Criterion, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text

@python_2_unicode_compatible
class Choice(models.Model):
    score = models.FloatField(default=0)

    def __str__(self):
        return str(self.score)

@python_2_unicode_compatible
class Vote(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (_("{user} voted at {choice} by {question}")
                .format(user=self.user, question=self.question,
                    choice=self.choice))

@python_2_unicode_compatible
class Count(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)

    def __str__(self):
        return (_("{count} users voted at {choice} by {question}")
                .format(count=self.count, question=self.question,
                        choice=self.choice))

@python_2_unicode_compatible
class Voting(models.Model):
    user = models.ForeignKey(User, unique=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (_('{user} voted at {time}')
                .format(user=self.user, time=self.last_modified))

extragrant/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

from .models import Question, Choice, Count

# Create your views here.

def index(request):
    questions = Question.objects.all()
    return render(request, 'polls/index.html', {'questions': questions})

def result(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    count_chart = []
    for count in question.count_set.order_by('choice__score').all():
        count_chart.append([count.choice.score, count.count])
    return render(request, 'polls/result.html', {'question': question, 'count_chart': count_chart})

def voting(request):
    return render(request, 'polls/voting.html', {'questions': Question.objects.all(), 'choices': Choice.objects.all()})

def recalc(request):
    if 'sure' in request.POST and request.POST['sure'] == "1":
        for question in Question.objects.all():
            for choice in Choice.objects.all():
                count, created = Count.objects.get_or_create(question=question, choice=choice)
                count.count = question.vote_set.filter(choice=choice).count()
                count.save()

            votes = question.vote_set.count()
            question.average_score = float(sum(count.count * count.choice.score for count in question.count_set.all())) / votes
            question.save()
        return HttpResponseRedirect(reverse('polls:index'))
    else:
        return render(request, 'polls/recalc.html')

extragrant/extragrant/templates/base.html
{% load i18n %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% trans "CMC extragrant system" %} - {% block title %} {% trans "Created by vslutov" %} {% endblock %}</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <style>
      body {
        min-height: 2000px;
        padding-top: 70px;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">{% trans "CMC extragrant system" %}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">{% trans "Home" %}</a></li>
            <li><a href="{% url 'polls:index' %}">{% trans "Polls" %}</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'auth_login' %}">{% trans "Login" %}</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/chartkick/2.0.0/chartkick.min.js"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

extragrant/polls/templates/polls/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block "content" %}
  <p>
    {% trans "You 're looking question:" %} {{question}}.
  </p>
  <p>
    {% trans "Average score:" %} {{question.average_score}}.
  </p>
{% endblock %}

extragrant/polls/templates/polls/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <h1>{% block title %} {% trans "Vote result" %} {% endblock %}</h1>
  <table class="table">
    <tr>
      <th>{% trans "Question" %}</th>
      <th>{% trans "Average score" %}</th>
    </tr>
    {% for question in questions %}
      <tr>
        <td><a href="{% url 'polls:result' question.id  %}">{{question}}</a></td>
        <td>{{question.average_score}}</td>
      </tr>
    {% endfor %}
  </table>
  <p><a href="{% url 'polls:recalc' %}" class="btn btn-danger">{% trans 'Recalc polls score' %}</a></p>
{% endblock %}

extragrant/polls/templates/polls/recalc.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <h1>{% block title %} {% trans "Are you sure want recalc polls score?" %} {% endblock %}</h1>
  <form method="post" action="{% url 'polls:recalc' %}">
    {% csrf_token %}
    <input type="hidden" name="sure" value="1">
	<a href="{% url 'polls:index' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    <button type="submit" class="btn btn-danger">{% trans 'Recalc' %}</button>
  </form>
{% endblock %}

extragrant/polls/templates/polls/result.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <h1>{% block title %} {% trans "Poll result" %} {% endblock %}</h1>
  <p>
    {% trans "You 're looking question:" %} {{ question }}.
  </p>
  <p>
    {% trans "Average score:" %} {{ question.average_score }}.
  </p>
  <div class="container">
    <div class="row">
      <div class="col-sm-4 hidden-xs">
        <div id="count_chart" style="height: 300px;"></div>
      </div>
    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script>
    $(function() {
        new Chartkick.ColumnChart("count_chart", {{ count_chart }});
    })
  </script>
{% endblock %}

extragrant/polls/templates/polls/voting.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <h1>{% block title %} {% trans "Voting" %} {% endblock %}</h1>
  {% if error_message %}<div class="alert alert-danger" role="alert">{{ error_message }}</div>{% endif %}

  <form action="{% url 'polls:voting' %}" method="post" class="form-horisontal container">
    {% csrf_token %}
    {% for question in questions %}
	  <div class="form-group container">
        <label for="question_{{question.id}}" class="col-sm-4 control-label">{{question}}</label>
        <div class="col-sm-8">
      	  {% for choice in choices %}
            <label class="radio-inline">
              <input type="radio" name="question_{{question.id}}" id="question_{{question.id}}_{{choice_id}}" value="{{choice.id}}"> {{choice}}
            </label>
	  	  {% endfor %}
        </div>
      </div>
    {% endfor %}
  <input type="submit" value="Vote" />
  </form>
{% endblock %}